[parameters]
radius = 2000                              # in AU
min_scale = 0.5                            # in AU
p_intensity = 4000
n_sink_points = 3000
dust = "jena_thin_e6.tab"
mol_data_files = ["hco+@xpol.dat"]
sampling = "UniformExact"
n_solve_iters = 14
reset_rng = false
collisional_partner_ids = [1]
nmol_weights = [1.0]
collisional_partner_names = ["H2"]
collisional_partner_mol_weights = [2.0159]

# One can specify multiple images by just adding another [[image]] section
[[images]]
nchan = 61
vel_res = 500.0
trans = 3
pxls = 100
img_res = 0.1
distance = 140.0
source_velocity = 0.0
azimuth = 0.0
inclination = 0.0
position_angle = 0.0
unit = "kelvin"
filename = "image_01.fits"
